/**
 * @fileoverview gRPC-Web generated client stub for rekam_medis
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: medical_record.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var encounter_pb = require('./encounter_pb.js')

var patient_pb = require('./patient_pb.js')
const proto = {};
proto.rekam_medis = require('./medical_record_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rekam_medis.PatientServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rekam_medis.PatientServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rekam_medis.GetPatientsRequest,
 *   !proto.rekam_medis.GetPatientsResponse>}
 */
const methodDescriptor_PatientService_GetPatients = new grpc.web.MethodDescriptor(
  '/rekam_medis.PatientService/GetPatients',
  grpc.web.MethodType.UNARY,
  patient_pb.GetPatientsRequest,
  patient_pb.GetPatientsResponse,
  /**
   * @param {!proto.rekam_medis.GetPatientsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  patient_pb.GetPatientsResponse.deserializeBinary
);


/**
 * @param {!proto.rekam_medis.GetPatientsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rekam_medis.GetPatientsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rekam_medis.GetPatientsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rekam_medis.PatientServiceClient.prototype.getPatients =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rekam_medis.PatientService/GetPatients',
      request,
      metadata || {},
      methodDescriptor_PatientService_GetPatients,
      callback);
};


/**
 * @param {!proto.rekam_medis.GetPatientsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rekam_medis.GetPatientsResponse>}
 *     Promise that resolves to the response
 */
proto.rekam_medis.PatientServicePromiseClient.prototype.getPatients =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rekam_medis.PatientService/GetPatients',
      request,
      metadata || {},
      methodDescriptor_PatientService_GetPatients);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rekam_medis.EncounterServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rekam_medis.EncounterServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rekam_medis.GetEncounterDetailsRequest,
 *   !proto.rekam_medis.GetEncounterDetailsResponse>}
 */
const methodDescriptor_EncounterService_GetEncounterDetails = new grpc.web.MethodDescriptor(
  '/rekam_medis.EncounterService/GetEncounterDetails',
  grpc.web.MethodType.UNARY,
  encounter_pb.GetEncounterDetailsRequest,
  encounter_pb.GetEncounterDetailsResponse,
  /**
   * @param {!proto.rekam_medis.GetEncounterDetailsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  encounter_pb.GetEncounterDetailsResponse.deserializeBinary
);


/**
 * @param {!proto.rekam_medis.GetEncounterDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rekam_medis.GetEncounterDetailsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rekam_medis.GetEncounterDetailsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rekam_medis.EncounterServiceClient.prototype.getEncounterDetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rekam_medis.EncounterService/GetEncounterDetails',
      request,
      metadata || {},
      methodDescriptor_EncounterService_GetEncounterDetails,
      callback);
};


/**
 * @param {!proto.rekam_medis.GetEncounterDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rekam_medis.GetEncounterDetailsResponse>}
 *     Promise that resolves to the response
 */
proto.rekam_medis.EncounterServicePromiseClient.prototype.getEncounterDetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rekam_medis.EncounterService/GetEncounterDetails',
      request,
      metadata || {},
      methodDescriptor_EncounterService_GetEncounterDetails);
};


module.exports = proto.rekam_medis;

