// source: polyclinic.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var helper_pb = require('./helper_pb.js');
goog.object.extend(proto, helper_pb);
goog.exportSymbol('proto.simrs.CompensateCreatePolyQueueEncounterRequest', null, global);
goog.exportSymbol('proto.simrs.CompensateCreatePolyQueueEncounterResponse', null, global);
goog.exportSymbol('proto.simrs.CreatePolyclinicQueueRequest', null, global);
goog.exportSymbol('proto.simrs.CreatePolyclinicQueueResponse', null, global);
goog.exportSymbol('proto.simrs.PolyclinicQueue', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.simrs.CreatePolyclinicQueueRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.simrs.CreatePolyclinicQueueRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.simrs.CreatePolyclinicQueueRequest.displayName = 'proto.simrs.CreatePolyclinicQueueRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.simrs.CreatePolyclinicQueueResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.simrs.CreatePolyclinicQueueResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.simrs.CreatePolyclinicQueueResponse.displayName = 'proto.simrs.CreatePolyclinicQueueResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.simrs.CompensateCreatePolyQueueEncounterRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.simrs.CompensateCreatePolyQueueEncounterRequest.displayName = 'proto.simrs.CompensateCreatePolyQueueEncounterRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.simrs.CompensateCreatePolyQueueEncounterResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.simrs.CompensateCreatePolyQueueEncounterResponse.displayName = 'proto.simrs.CompensateCreatePolyQueueEncounterResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.simrs.PolyclinicQueue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.simrs.PolyclinicQueue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.simrs.PolyclinicQueue.displayName = 'proto.simrs.PolyclinicQueue';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.simrs.CreatePolyclinicQueueRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.simrs.CreatePolyclinicQueueRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.simrs.CreatePolyclinicQueueRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CreatePolyclinicQueueRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    queue: (f = msg.getQueue()) && proto.simrs.PolyclinicQueue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.simrs.CreatePolyclinicQueueRequest}
 */
proto.simrs.CreatePolyclinicQueueRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.simrs.CreatePolyclinicQueueRequest;
  return proto.simrs.CreatePolyclinicQueueRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.simrs.CreatePolyclinicQueueRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.simrs.CreatePolyclinicQueueRequest}
 */
proto.simrs.CreatePolyclinicQueueRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.simrs.PolyclinicQueue;
      reader.readMessage(value,proto.simrs.PolyclinicQueue.deserializeBinaryFromReader);
      msg.setQueue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.simrs.CreatePolyclinicQueueRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.simrs.CreatePolyclinicQueueRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.simrs.CreatePolyclinicQueueRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CreatePolyclinicQueueRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQueue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.simrs.PolyclinicQueue.serializeBinaryToWriter
    );
  }
};


/**
 * optional PolyclinicQueue queue = 1;
 * @return {?proto.simrs.PolyclinicQueue}
 */
proto.simrs.CreatePolyclinicQueueRequest.prototype.getQueue = function() {
  return /** @type{?proto.simrs.PolyclinicQueue} */ (
    jspb.Message.getWrapperField(this, proto.simrs.PolyclinicQueue, 1));
};


/**
 * @param {?proto.simrs.PolyclinicQueue|undefined} value
 * @return {!proto.simrs.CreatePolyclinicQueueRequest} returns this
*/
proto.simrs.CreatePolyclinicQueueRequest.prototype.setQueue = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.simrs.CreatePolyclinicQueueRequest} returns this
 */
proto.simrs.CreatePolyclinicQueueRequest.prototype.clearQueue = function() {
  return this.setQueue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.simrs.CreatePolyclinicQueueRequest.prototype.hasQueue = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.simrs.CreatePolyclinicQueueResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.simrs.CreatePolyclinicQueueResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CreatePolyclinicQueueResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errormessage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.simrs.CreatePolyclinicQueueResponse}
 */
proto.simrs.CreatePolyclinicQueueResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.simrs.CreatePolyclinicQueueResponse;
  return proto.simrs.CreatePolyclinicQueueResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.simrs.CreatePolyclinicQueueResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.simrs.CreatePolyclinicQueueResponse}
 */
proto.simrs.CreatePolyclinicQueueResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.simrs.CreatePolyclinicQueueResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.simrs.CreatePolyclinicQueueResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CreatePolyclinicQueueResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrormessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 code = 1;
 * @return {number}
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.CreatePolyclinicQueueResponse} returns this
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.simrs.CreatePolyclinicQueueResponse} returns this
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string errorMessage = 3;
 * @return {string}
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.getErrormessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.simrs.CreatePolyclinicQueueResponse} returns this
 */
proto.simrs.CreatePolyclinicQueueResponse.prototype.setErrormessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.simrs.CompensateCreatePolyQueueEncounterRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.simrs.CompensateCreatePolyQueueEncounterRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    queueid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    actorid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    encounterid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterRequest}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.simrs.CompensateCreatePolyQueueEncounterRequest;
  return proto.simrs.CompensateCreatePolyQueueEncounterRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.simrs.CompensateCreatePolyQueueEncounterRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterRequest}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQueueid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setActorid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEncounterid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.simrs.CompensateCreatePolyQueueEncounterRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.simrs.CompensateCreatePolyQueueEncounterRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQueueid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getActorid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getEncounterid();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional int64 queueId = 1;
 * @return {number}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.getQueueid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterRequest} returns this
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.setQueueid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 actorId = 2;
 * @return {number}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.getActorid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterRequest} returns this
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.setActorid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 encounterId = 3;
 * @return {number}
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.getEncounterid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterRequest} returns this
 */
proto.simrs.CompensateCreatePolyQueueEncounterRequest.prototype.setEncounterid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.simrs.CompensateCreatePolyQueueEncounterResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.simrs.CompensateCreatePolyQueueEncounterResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errormessage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterResponse}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.simrs.CompensateCreatePolyQueueEncounterResponse;
  return proto.simrs.CompensateCreatePolyQueueEncounterResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.simrs.CompensateCreatePolyQueueEncounterResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterResponse}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.simrs.CompensateCreatePolyQueueEncounterResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.simrs.CompensateCreatePolyQueueEncounterResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrormessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 code = 1;
 * @return {number}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterResponse} returns this
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterResponse} returns this
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string errorMessage = 3;
 * @return {string}
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.getErrormessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.simrs.CompensateCreatePolyQueueEncounterResponse} returns this
 */
proto.simrs.CompensateCreatePolyQueueEncounterResponse.prototype.setErrormessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.simrs.PolyclinicQueue.prototype.toObject = function(opt_includeInstance) {
  return proto.simrs.PolyclinicQueue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.simrs.PolyclinicQueue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.PolyclinicQueue.toObject = function(includeInstance, msg) {
  var f, obj = {
    idqueue: jspb.Message.getFieldWithDefault(msg, 1, 0),
    queuenumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    idencounter: jspb.Message.getFieldWithDefault(msg, 3, 0),
    mrnumber: jspb.Message.getFieldWithDefault(msg, 4, ""),
    room: (f = msg.getRoom()) && helper_pb.HelperVar.toObject(includeInstance, f),
    queuestatus: (f = msg.getQueuestatus()) && helper_pb.HelperVar.toObject(includeInstance, f),
    generalpractitioner: (f = msg.getGeneralpractitioner()) && helper_pb.HelperVar.toObject(includeInstance, f),
    accounting: (f = msg.getAccounting()) && helper_pb.Accounting.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.simrs.PolyclinicQueue}
 */
proto.simrs.PolyclinicQueue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.simrs.PolyclinicQueue;
  return proto.simrs.PolyclinicQueue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.simrs.PolyclinicQueue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.simrs.PolyclinicQueue}
 */
proto.simrs.PolyclinicQueue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIdqueue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQueuenumber(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIdencounter(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMrnumber(value);
      break;
    case 5:
      var value = new helper_pb.HelperVar;
      reader.readMessage(value,helper_pb.HelperVar.deserializeBinaryFromReader);
      msg.setRoom(value);
      break;
    case 6:
      var value = new helper_pb.HelperVar;
      reader.readMessage(value,helper_pb.HelperVar.deserializeBinaryFromReader);
      msg.setQueuestatus(value);
      break;
    case 7:
      var value = new helper_pb.HelperVar;
      reader.readMessage(value,helper_pb.HelperVar.deserializeBinaryFromReader);
      msg.setGeneralpractitioner(value);
      break;
    case 8:
      var value = new helper_pb.Accounting;
      reader.readMessage(value,helper_pb.Accounting.deserializeBinaryFromReader);
      msg.setAccounting(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.simrs.PolyclinicQueue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.simrs.PolyclinicQueue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.simrs.PolyclinicQueue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.simrs.PolyclinicQueue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdqueue();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getQueuenumber();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getIdencounter();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getMrnumber();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRoom();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      helper_pb.HelperVar.serializeBinaryToWriter
    );
  }
  f = message.getQueuestatus();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      helper_pb.HelperVar.serializeBinaryToWriter
    );
  }
  f = message.getGeneralpractitioner();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      helper_pb.HelperVar.serializeBinaryToWriter
    );
  }
  f = message.getAccounting();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      helper_pb.Accounting.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 idQueue = 1;
 * @return {number}
 */
proto.simrs.PolyclinicQueue.prototype.getIdqueue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.setIdqueue = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 queueNumber = 2;
 * @return {number}
 */
proto.simrs.PolyclinicQueue.prototype.getQueuenumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.setQueuenumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 iDEncounter = 3;
 * @return {number}
 */
proto.simrs.PolyclinicQueue.prototype.getIdencounter = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.setIdencounter = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string mrNumber = 4;
 * @return {string}
 */
proto.simrs.PolyclinicQueue.prototype.getMrnumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.setMrnumber = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional HelperVar room = 5;
 * @return {?proto.simrs.HelperVar}
 */
proto.simrs.PolyclinicQueue.prototype.getRoom = function() {
  return /** @type{?proto.simrs.HelperVar} */ (
    jspb.Message.getWrapperField(this, helper_pb.HelperVar, 5));
};


/**
 * @param {?proto.simrs.HelperVar|undefined} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
*/
proto.simrs.PolyclinicQueue.prototype.setRoom = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.clearRoom = function() {
  return this.setRoom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.simrs.PolyclinicQueue.prototype.hasRoom = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional HelperVar queueStatus = 6;
 * @return {?proto.simrs.HelperVar}
 */
proto.simrs.PolyclinicQueue.prototype.getQueuestatus = function() {
  return /** @type{?proto.simrs.HelperVar} */ (
    jspb.Message.getWrapperField(this, helper_pb.HelperVar, 6));
};


/**
 * @param {?proto.simrs.HelperVar|undefined} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
*/
proto.simrs.PolyclinicQueue.prototype.setQueuestatus = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.clearQueuestatus = function() {
  return this.setQueuestatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.simrs.PolyclinicQueue.prototype.hasQueuestatus = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional HelperVar generalPractitioner = 7;
 * @return {?proto.simrs.HelperVar}
 */
proto.simrs.PolyclinicQueue.prototype.getGeneralpractitioner = function() {
  return /** @type{?proto.simrs.HelperVar} */ (
    jspb.Message.getWrapperField(this, helper_pb.HelperVar, 7));
};


/**
 * @param {?proto.simrs.HelperVar|undefined} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
*/
proto.simrs.PolyclinicQueue.prototype.setGeneralpractitioner = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.clearGeneralpractitioner = function() {
  return this.setGeneralpractitioner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.simrs.PolyclinicQueue.prototype.hasGeneralpractitioner = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Accounting accounting = 8;
 * @return {?proto.simrs.Accounting}
 */
proto.simrs.PolyclinicQueue.prototype.getAccounting = function() {
  return /** @type{?proto.simrs.Accounting} */ (
    jspb.Message.getWrapperField(this, helper_pb.Accounting, 8));
};


/**
 * @param {?proto.simrs.Accounting|undefined} value
 * @return {!proto.simrs.PolyclinicQueue} returns this
*/
proto.simrs.PolyclinicQueue.prototype.setAccounting = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.simrs.PolyclinicQueue} returns this
 */
proto.simrs.PolyclinicQueue.prototype.clearAccounting = function() {
  return this.setAccounting(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.simrs.PolyclinicQueue.prototype.hasAccounting = function() {
  return jspb.Message.getField(this, 8) != null;
};


goog.object.extend(exports, proto.simrs);
