// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: emergency_room.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddERPatientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErPatient *ERPatient `protobuf:"bytes,1,opt,name=erPatient,proto3" json:"erPatient,omitempty"`
}

func (x *AddERPatientRequest) Reset() {
	*x = AddERPatientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emergency_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddERPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddERPatientRequest) ProtoMessage() {}

func (x *AddERPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emergency_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddERPatientRequest.ProtoReflect.Descriptor instead.
func (*AddERPatientRequest) Descriptor() ([]byte, []int) {
	return file_emergency_room_proto_rawDescGZIP(), []int{0}
}

func (x *AddERPatientRequest) GetErPatient() *ERPatient {
	if x != nil {
		return x.ErPatient
	}
	return nil
}

type CompensateAddERPatientEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueueId     int64 `protobuf:"varint,1,opt,name=queueId,proto3" json:"queueId,omitempty"`
	ActorId     int64 `protobuf:"varint,2,opt,name=actorId,proto3" json:"actorId,omitempty"`
	EncounterId int64 `protobuf:"varint,3,opt,name=encounterId,proto3" json:"encounterId,omitempty"`
}

func (x *CompensateAddERPatientEncounterRequest) Reset() {
	*x = CompensateAddERPatientEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emergency_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompensateAddERPatientEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensateAddERPatientEncounterRequest) ProtoMessage() {}

func (x *CompensateAddERPatientEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emergency_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensateAddERPatientEncounterRequest.ProtoReflect.Descriptor instead.
func (*CompensateAddERPatientEncounterRequest) Descriptor() ([]byte, []int) {
	return file_emergency_room_proto_rawDescGZIP(), []int{1}
}

func (x *CompensateAddERPatientEncounterRequest) GetQueueId() int64 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *CompensateAddERPatientEncounterRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *CompensateAddERPatientEncounterRequest) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

// Model definitions
type ERPatient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdQueue     int64       `protobuf:"varint,1,opt,name=idQueue,proto3" json:"idQueue,omitempty"`
	IdEncounter int64       `protobuf:"varint,2,opt,name=idEncounter,proto3" json:"idEncounter,omitempty"`
	MrNumber    string      `protobuf:"bytes,3,opt,name=mrNumber,proto3" json:"mrNumber,omitempty"`
	Room        *HelperVar  `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	Note        string      `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Accounting  *Accounting `protobuf:"bytes,7,opt,name=accounting,proto3" json:"accounting,omitempty"`
}

func (x *ERPatient) Reset() {
	*x = ERPatient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emergency_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ERPatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ERPatient) ProtoMessage() {}

func (x *ERPatient) ProtoReflect() protoreflect.Message {
	mi := &file_emergency_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ERPatient.ProtoReflect.Descriptor instead.
func (*ERPatient) Descriptor() ([]byte, []int) {
	return file_emergency_room_proto_rawDescGZIP(), []int{2}
}

func (x *ERPatient) GetIdQueue() int64 {
	if x != nil {
		return x.IdQueue
	}
	return 0
}

func (x *ERPatient) GetIdEncounter() int64 {
	if x != nil {
		return x.IdEncounter
	}
	return 0
}

func (x *ERPatient) GetMrNumber() string {
	if x != nil {
		return x.MrNumber
	}
	return ""
}

func (x *ERPatient) GetRoom() *HelperVar {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *ERPatient) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ERPatient) GetAccounting() *Accounting {
	if x != nil {
		return x.Accounting
	}
	return nil
}

// Generic Encounter Service Response
type GenericERServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message      string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *GenericERServiceResponse) Reset() {
	*x = GenericERServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emergency_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericERServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericERServiceResponse) ProtoMessage() {}

func (x *GenericERServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emergency_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericERServiceResponse.ProtoReflect.Descriptor instead.
func (*GenericERServiceResponse) Descriptor() ([]byte, []int) {
	return file_emergency_room_proto_rawDescGZIP(), []int{3}
}

func (x *GenericERServiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenericERServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenericERServiceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_emergency_room_proto protoreflect.FileDescriptor

var file_emergency_room_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x69, 0x6d, 0x72, 0x73, 0x1a, 0x0c, 0x68,
	0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x13, 0x41,
	0x64, 0x64, 0x45, 0x52, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x65, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x69, 0x6d, 0x72, 0x73, 0x2e, 0x45, 0x52,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x22, 0x7e, 0x0a, 0x26, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x45, 0x52, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x09, 0x45, 0x52, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x69, 0x64, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x64,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x69, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x69, 0x6d, 0x72, 0x73, 0x2e, 0x48,
	0x65, 0x6c, 0x70, 0x65, 0x72, 0x56, 0x61, 0x72, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x69, 0x6d, 0x72, 0x73, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x6c, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63,
	0x45, 0x52, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emergency_room_proto_rawDescOnce sync.Once
	file_emergency_room_proto_rawDescData = file_emergency_room_proto_rawDesc
)

func file_emergency_room_proto_rawDescGZIP() []byte {
	file_emergency_room_proto_rawDescOnce.Do(func() {
		file_emergency_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_emergency_room_proto_rawDescData)
	})
	return file_emergency_room_proto_rawDescData
}

var file_emergency_room_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_emergency_room_proto_goTypes = []interface{}{
	(*AddERPatientRequest)(nil),                    // 0: simrs.AddERPatientRequest
	(*CompensateAddERPatientEncounterRequest)(nil), // 1: simrs.CompensateAddERPatientEncounterRequest
	(*ERPatient)(nil),                              // 2: simrs.ERPatient
	(*GenericERServiceResponse)(nil),               // 3: simrs.GenericERServiceResponse
	(*HelperVar)(nil),                              // 4: simrs.HelperVar
	(*Accounting)(nil),                             // 5: simrs.Accounting
}
var file_emergency_room_proto_depIdxs = []int32{
	2, // 0: simrs.AddERPatientRequest.erPatient:type_name -> simrs.ERPatient
	4, // 1: simrs.ERPatient.room:type_name -> simrs.HelperVar
	5, // 2: simrs.ERPatient.accounting:type_name -> simrs.Accounting
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_emergency_room_proto_init() }
func file_emergency_room_proto_init() {
	if File_emergency_room_proto != nil {
		return
	}
	file_helper_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_emergency_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddERPatientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emergency_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompensateAddERPatientEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emergency_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ERPatient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emergency_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericERServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emergency_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emergency_room_proto_goTypes,
		DependencyIndexes: file_emergency_room_proto_depIdxs,
		MessageInfos:      file_emergency_room_proto_msgTypes,
	}.Build()
	File_emergency_room_proto = out.File
	file_emergency_room_proto_rawDesc = nil
	file_emergency_room_proto_goTypes = nil
	file_emergency_room_proto_depIdxs = nil
}
